### ISSUE TITLE
while using GEMINI API KEY--Warning: 'next_agent' key not found in RouterAgent response. Defaulting to 'default_agent'.

### ISSUE THREAD

**Issue by Richardson143** [john-adeojo/graph_websearch_agent#6]
Traceback (most recent call last):
  File "E:\Appdata\program files\python\projects\graph_websearch_agent\.venv\Lib\site-packages\chainlit\utils.py", line 40, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Appdata\program files\python\projects\graph_websearch_agent\app/chat.py", line 194, in main
    response = await cl.make_async(chat_workflow.invoke_workflow)(message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Appdata\program files\python\projects\graph_websearch_agent\.venv\Lib\site-packages\asyncer\_main.py", line 358, in wrapper
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Appdata\program files\python\projects\graph_websearch_agent\.venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Appdata\program files\python\projects\graph_websearch_agent\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "E:\Appdata\program files\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "E:\Appdata\program files\Lib\asyncio\tasks.py", line 385, in __wakeup
    future.result()
  File "E:\Appdata\program files\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "E:\Appdata\program files\python\projects\graph_websearch_agent\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Appdata\program files\python\projects\graph_websearch_agent\app/chat.py", line 68, in invoke_workflow
    next_agent_value = reviewer_state_dict["next_agent"]
                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'next_agent'

**Comment by john-adeojo** [comment]
What REQUEST RESPONSE error code did you get? This should be printed in white in your cmd prompt or powershell.

**Comment by Richardson143** [comment]
Request Response - 429

**Comment by john-adeojo** [comment]
429 means too many requests, you're probably on the free plan for gemini so you're hitting rate limits. That's why the "next_agent" key is missing, the model hasn't generated anything.

**Comment by Richardson143** [comment]
![image](https://github.com/john-adeojo/graph_websearch_agent/assets/155881268/502ee913-a2e5-4be2-83b3-57a2cd79c37b)

yes, I was using the Free plan of Gemini Maybe that was the issue but it should be a rate limit error, and even when I tried with Groq the error for rate limit is so clear  -REQUEST RESPONSE 400-"Recursion limit of 40 reached without hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key."

**Comment by john-adeojo** [comment]
recursion_limit means the workflow cycled through 40 iterations without being able to answer your question. You can increase this on the settings menu in the front end. For Gemini 429 error means you have exceeded your request quota https://cloud.google.com/vertex-ai/docs/general/troubleshooting?component=any#error_code_429. If your question is complex, it might take the workflow several iterations before it can get to an answer, so try increasing the recursion limit.
